apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-api
spec:
   selector:
    matchLabels:
      app: prod-svc-api
   template:
     metadata:
      labels:
        app: prod-svc-api
     spec:
        
        nodeSelector:
          eks.amazonaws.com/nodegroup: production-ml-eu-swf-app-ng

