apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../application
namespace: prod
namePrefix: prod-
patchesStrategicMerge:
  - deploymnet.yaml
  - service.yml
commonLabels:
        app: prod-test-svc
